VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsAeSocketEvent"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Implements aeSocketEvent

'Public Sub aeSocketEvent_Opened( _
    ByVal RemotePeer As String, ByVal RemotePort As Long, _
    ByVal LocalPeer As String, ByVal LocalPort As Long, _
    ByVal bFromListen As Boolean)
'End Sub

'Public Sub aeSocketEvent_Closed( _
    ByVal RemotePeer As String, _
    ByVal RemotePort As Long, _
    ByVal bRemoteClosure As Boolean, _
    ByVal bGrace As Boolean, _
    ByVal bKeptData As Boolean)
'End Sub

'Public Sub aeSocketEvent_Error( _
    ByVal ErrorCode As Long, _
    ByVal ErrorString As String)
    
    'Events_ErrorTxt ErrorCode, "Socket Error : " & ErrorString
    
'End Sub

'Public Sub aeSocketEvent_AcceptConnection( _
    ByVal RemotePeer As String, _
    ByVal RemotePort As Long, _
    ByVal SocketID As Long)
'End Sub

'Public Sub aeSocketEvent_DNSLookUpStarted( _
'  ByVal Host As String, ByVal bIsHost As Boolean)
'End Sub

'Public Sub aeSocketEvent_DNSLookUpDone( _
  ByVal Host As String, _
  ByVal bIsHost As Boolean, _
  ByVal PassedHost As String, _
  ByVal bError As Boolean, _
  ByVal ErrorCode As Long, _
  ByVal ErrorCodeMessage As String)
'End Sub

'Public Sub aeSocketEvent_StateChanged( _
  ByVal NewState As aeSocketState)
'End Sub

'Public Sub aeSocketEvent_SocketChanged( _
  ByVal NewHandle As Long, _
  ByVal SelfPtr As Long)
'End Sub

'Public Sub aeSocketEvent_DataRead( _
  ByVal BufferLen As Long, _
  ByVal Buffered As aeSocketReadDataEnum, _
  ByVal DataPtr As Long, _
  Data() As Byte, _
  ByVal IsOOB As Boolean)
  
'  Recv_DataArrival StrConv(Data, vbUnicode)
  
'End Sub

'Public Sub aeSocketEvent_Binded( _
  ByVal Port As Long, _
  ByVal bRemote As Boolean)
'End Sub

'Public Sub aeSocketEvent_thisaeSocket(ByVal ido As aeSocket)
'End Sub


